# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Catalyst-Plugin-Email-Page
version:      v0.0.1
version_from: lib/Catalyst/Plugin/Email/Page.pm
installdirs:  site
requires:
    Catalyst:                      5.61
    Catalyst::Request:             0
    Readonly:                      0
    Test::More:                    0
    version:                       0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
